config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root({:to=>"home#index"})
  get 'picture/show'
  match '/picture', to: 'picture#show', via: 'get'
  resources :potholes
  post 'picture/mystore'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
belongs_to:pothole
mount_uploader :id, MyuploaderUploader 
end

app/models/pothole.rb
class Pothole < ApplicationRecord

validates :streetAdress, :presence => true
validates :size, :numericality =>{greater_than: 0,less_than_or_equal_to:10}
validates :location, :presence => true
validates :district, :presence => true

has_many :picture
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
   def show
	puts("show params", params)

     @pothole = Pothole.find(params[:pothole_id])
     @picture = @pothole.picture unless @pothole.nil?
  end


  def mystore
    up_file = params[:localfile]
puts("up_file", up_file)
	pothole_id = params[:pothole_id]
puts("pothole_id", pothole_id)
     myfile = MyuploaderUploader.new()
     myfile.store!(up_file)
	# puts("111111111111111111111111111111")
	path = myfile.to_s
	# puts(s)
	@newpicture = Picture.new(:path => path, :pothole_id => pothole_id )
	@newpicture.save
	redirect_to picture_path(:pothole_id => @newpicture.pothole_id)

    
  end

end

app/controllers/potholes_controller.rb
class PotholesController < ApplicationController
  before_action :set_pothole, only: [:show, :edit, :update, :destroy]

  # GET /potholes
  # GET /potholes.json
  def index
    @potholes = Pothole.all
  end

  # GET /potholes/1
  # GET /potholes/1.json
  def show
  end

  # GET /potholes/new
  def new
    @pothole = Pothole.new
  end

  # GET /potholes/1/edit
  def edit
  end

  # POST /potholes
  # POST /potholes.json
  def create
    @pothole = Pothole.new(pothole_params)

    respond_to do |format|
      if @pothole.save
        format.html { redirect_to @pothole, notice: 'Pothole was successfully created.' }
        format.json { render :show, status: :created, location: @pothole }
      else
        format.html { render :new }
        format.json { render json: @pothole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /potholes/1
  # PATCH/PUT /potholes/1.json
  def update
    respond_to do |format|
      if @pothole.update(pothole_params)
        format.html { redirect_to @pothole, notice: 'Pothole was successfully updated.' }
        format.json { render :show, status: :ok, location: @pothole }
      else
        format.html { render :edit }
        format.json { render json: @pothole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /potholes/1
  # DELETE /potholes/1.json
  def destroy
    @pothole.destroy
    respond_to do |format|
      format.html { redirect_to potholes_url, notice: 'Pothole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pothole
      @pothole = Pothole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pothole_params
      params.require(:pothole).permit(:streetAdress, :size, :location, :district)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/potholes_helper.rb
module PotholesHelper
end

app/views/home/index.html.erb
<h1  align="center">Welcome to PHTRS system</h1>
<h3 align="center"> <%= link_to "Submit pothole", potholes_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/picture/show.html.erb
<h1>Pothole Picture Show</h1>



<%= form_tag '/picture/mystore' , :multipart => true do%>
    <%= file_field_tag :localfile %>  
    <%= hidden_field_tag :pothole_id, params[:pothole_id]%> 
    <%= submit_tag "Upload"%>
<% end %>

<ul id="pictures_list">
	<% @picture.each do |pic| -%>
	<li><%= image_tag pic.path.to_s -%>
	</li>
	<% end -%>
</ul>

app/views/potholes/_form.html.erb
<%= form_with(model: pothole, local: true) do |form| %>
  <% if pothole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pothole.errors.count, "error") %> prohibited this pothole from being saved:</h2>

      <ul>
      <% pothole.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :streetAdress %>
    <%= form.text_field :streetAdress, id: :pothole_streetAdress %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size, id: :pothole_size %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :pothole_location %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district, id: :pothole_district %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/potholes/edit.html.erb
<h1>Editing Pothole</h1>

<%= render 'form', pothole: @pothole %>

<%= link_to 'Show', @pothole %> |
<%= link_to 'Back', potholes_path %>

app/views/potholes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Potholes</h1>

<table>
  <thead>
    <tr>
      <th>Streetadress</th>
      <th>Size</th>
      <th>Location</th>
      <th>District</th>
      <th>RepairPriority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @potholes.each do |pothole| %>
      <tr>
        <td><%= pothole.streetAdress %></td>
        <td><%= pothole.size %></td>
        <td><%= pothole.location %></td>
        <td><%= pothole.district %></td>
	<td><%= 10-pothole.size %></td>
        <td><%= link_to 'Show', pothole %></td>
        <td><%= link_to 'Edit', edit_pothole_path(pothole) %></td>
        <td><%= link_to 'Destroy', pothole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'picture', picture_path(pothole_id: pothole.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pothole', new_pothole_path %>

app/views/potholes/new.html.erb
<h1>New Pothole</h1>

<%= render 'form', pothole: @pothole %>

<%= link_to 'Back', potholes_path %>

app/views/potholes/o_form.html.erb
<%= form_with(model: pothole, local: true) do |form| %>
  <% if pothole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pothole.errors.count, "error") %> prohibited this pothole from being saved:</h2>

      <ul>
      <% pothole.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :streetAdress %>
    <%= form.text_field :streetAdress, id: :pothole_streetAdress %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size, id: :pothole_size %>
  </div>

  <div class="field">
    <%= form.label :location %>
	
    <%= form.text_field :location, id: :pothole_location %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district, id: :pothole_district %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/potholes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Streetadress:</strong>
  <%= @pothole.streetAdress %>
</p>

<p>
  <strong>Size:</strong>
  <%= @pothole.size %>
</p>

<p>
  <strong>Location:</strong>
  <%= @pothole.location %>
</p>

<p>
  <strong>District:</strong>
  <%= @pothole.district %>
</p>

<%= link_to 'Edit', edit_pothole_path(@pothole) %> |
<%= link_to 'Back', potholes_path %>